version: '3.8'

services:
  db:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  spring_boot_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: your_jwt_secret_key_here  # 추가된 환경 변수
      JWT_EXPIRATION: 3600000  # 추가된 환경 변수 (예: 1시간)
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    restart: on-failure

networks:
  mynetwork:
